#!/bin/sh
VSCODE_GIT_GRAPH_ASKPASS_PIPE=`mktemp` || exit 1
trap 'rm -f "$VSCODE_GIT_GRAPH_ASKPASS_PIPE"' EXIT
VSCODE_GIT_GRAPH_ASKPASS_PIPE="$VSCODE_GIT_GRAPH_ASKPASS_PIPE" VSCODE_GIT_GRAPH_ASKPASS_TYPE="https" "$VSCODE_GIT_GRAPH_ASKPASS_NODE" "$VSCODE_GIT_GRAPH_ASKPASS_MAIN" $* || exit 1
cat "$VSCODE_GIT_GRAPH_ASKPASS_PIPE"
